### ISSUE TITLE
project status

### ISSUE THREAD

**Issue by M1cha** [seiyanuta/v8-uefi-test#1]
what's the status of this project?
the files in "src" don't look like they'd power up v8.

**Comment by seiyanuta** [comment]
You're right. This is incomplete and work-in-progress project. I'll create a new repository with an appreciate name when this become ready for try out. I guess it would be in September because I'm busy in these months.

**Comment by seiyanuta** [comment]
I'll close this issue. Please reopen or open new one if you want to ask the progress again.
